name: NPM testing and publish package

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci --legacy-peer-deps
      - run: npm test
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress install
        run: npm install --legacy-peer-deps
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          install: false
          component: true
  publish-npm:
    needs: [ build, cypress-run ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci --legacy-peer-deps
      - run: npm run build
        env:
          LIBRARY_NAME: "@aleleba/ro-ut-ui"
          EXTERNAL_CSS: "true"
      - run: npm publish --access=public
        env:
          LIBRARY_NAME: "@aleleba/ro-ut-ui"
          EXTERNAL_CSS: "true"
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}